from braillebase import BrailleBase

class BrailleBasePortuguese(BrailleBase):
    def __init__(self):

        """

        """
        super().__init__()
        #letras min
        self.append_braille_letter("a", ["⠁"])
        self.append_braille_letter("b", ["⠃"])
        self.append_braille_letter("c", ["⠉"])
        self.append_braille_letter("d", ["⠙"])
        self.append_braille_letter("e", ["⠑"])
        self.append_braille_letter("f", ["⠋"])
        self.append_braille_letter("g", ["⠛"])
        self.append_braille_letter("h", ["⠓"])
        self.append_braille_letter("i", ["⠊"])
        self.append_braille_letter("j", ["⠚"])
        self.append_braille_letter("k", ["⠅"])
        self.append_braille_letter("l", ["⠇"])
        self.append_braille_letter("m", ["⠍"])
        self.append_braille_letter("n", ["⠝"])
        self.append_braille_letter("o", ["⠕"])
        self.append_braille_letter("p", ["⠏"])
        self.append_braille_letter("q", ["⠟"])
        self.append_braille_letter("r", ["⠗"])
        self.append_braille_letter("s", ["⠎"])
        self.append_braille_letter("t", ["⠞"])
        self.append_braille_letter("u", ["⠥"])
        self.append_braille_letter("v", ["⠧"])
        self.append_braille_letter("w", ["⠺"]) 
        self.append_braille_letter("x", ["⠭"])
        self.append_braille_letter("y", ["⠽"])
        self.append_braille_letter("z", ["⠵"])
       #letras maiusc
        self.append_special_braille_lettr_rules01("A", ["⠁"])
        self.append_special_braille_lettr_rules01("B", ["⠃"])
        self.append_special_braille_lettr_rules01("C", ["⠉"])
        self.append_special_braille_lettr_rules01("D", ["⠙"])
        self.append_special_braille_lettr_rules01("E", ["⠑"])
        self.append_special_braille_lettr_rules01("F", ["⠋"])
        self.append_special_braille_lettr_rules01("G", ["⠛"])
        self.append_special_braille_lettr_rules01("H", ["⠓"])
        self.append_special_braille_lettr_rules01("I", ["⠊"])
        self.append_special_braille_lettr_rules01("J", ["⠚"])
        self.append_special_braille_lettr_rules01("K", ["⠅"])
        self.append_special_braille_lettr_rules01("L", ["⠇"])
        self.append_special_braille_lettr_rules01("M", ["⠍"])
        self.append_special_braille_lettr_rules01("N", ["⠝"])
        self.append_special_braille_lettr_rules01("O", ["⠕"])
        self.append_special_braille_lettr_rules01("P", ["⠏"])
        self.append_special_braille_lettr_rules01("Q", ["⠟"])
        self.append_special_braille_lettr_rules01("R", ["⠗"])
        self.append_special_braille_lettr_rules01("S", ["⠎"])
        self.append_special_braille_lettr_rules01("T", ["⠞"])
        self.append_special_braille_lettr_rules01("U", ["⠥"])
        self.append_special_braille_lettr_rules01("V", ["⠧"])
        self.append_special_braille_lettr_rules01("W", ["⠺"])
        self.append_special_braille_lettr_rules01("X", ["⠭"])
        self.append_special_braille_lettr_rules01("Y", ["⠽"])
        self.append_special_braille_lettr_rules01("Z", ["⠵"])
        #number
        self.append_braille_letter("⠼", ["⠼"])
        self.append_braille_letter("1", ["⠁"])
        self.append_braille_letter("2", ["⠃"])
        self.append_braille_letter("3", ["⠉"])
        self.append_braille_letter("4", ["⠙"])
        self.append_braille_letter("5", ["⠑"])
        self.append_braille_letter("6", ["⠋"])
        self.append_braille_letter("7", ["⠛"])
        self.append_braille_letter("8", ["⠓"])
        self.append_braille_letter("9", ["⠊"])
        self.append_braille_letter("0", ["⠚"])
        #math
        self.append_braille_letter("%", ["⠨", "⠴"])
        #Simbol
        self.append_braille_letter(".", ["⠲"])
        self.append_braille_letter(",", ["⠂"])
        self.append_braille_letter(";", ["⠆"])
        self.append_braille_letter(":", ["⠒"])
        self.append_braille_letter("?", ["⠢"])
        self.append_braille_letter("!", ["⠖"])
        self.append_braille_letter("(", ["⠶"])
        self.append_braille_letter(")", ["⠶"])
        self.append_braille_letter("-", ["⠤"])
        self.append_braille_letter("…", ["⠄", "⠄", "⠄"])
        self.append_braille_letter("‘", ["⠄", "⠦"])
        self.append_braille_letter("’", ["⠄", "⠴"])
        self.append_braille_letter("—", ["⠤", "⠤"])
        self.append_braille_letter("–", ["⠤"])
        self.append_braille_letter("°", ["⠘", "⠚"])
        self.append_braille_letter("«", ["⠶", "⠦"])
        self.append_braille_letter("»", ["⠶", "⠴"])
        self.append_braille_letter("'", ["⠄"])
        self.append_braille_letter("@", ["⠈", "⠁"])
        self.append_braille_letter("$", ["⠈", "⠎"])
        self.append_braille_letter("€", ["⠈", "⠑"])
        self.append_braille_letter("£", ["⠈", "⠇"])
        self.append_braille_letter("|", ["⠸", "⠳"])
        self.append_braille_letter("_", ["⠸", "⠤"])
        #jus
        self.append_braille_letter("§", ["⠘", "⠎"])
        self.append_braille_letter("º", ["⠚"])
        self.append_braille_letter("ª", ["⠁"])
        self.append_braille_letter("°", ["⠘", "⠚"])
        self.append_braille_letter("※", ["⠔"])

        self.append_braille_letter("\u002F", ["⠌"])      # /
        self.append_braille_letter("\u005C", ["⠸", "⠌"]) # \
        self.append_braille_letter("\u201C", ["⠦"]) # “
        self.append_braille_letter("\u201D", ["⠴"]) # ”
        
        #self.append_special_braille_letter("I", ["⠠", "⠊"])
        #self.append_special_braille_letter("II", ["⠠", "⠊", "⠊"])
        #self.append_special_braille_letter("III", ["⠠", "⠊", "⠊", "⠊"])
        #self.append_special_braille_letter("IV", ["⠠", "⠊", "⠧"])
        #self.append_special_braille_letter("art.", ["⠼", "⠁"])


#TEST
#bb = BrailleBasePortuguese()
#print(bb.output_braille_txt("AAaAAAaaaAa 112233aA"))